Feature/ch7658/andresa docker dsb revisar template data science api
Data-Science-Brigade/dsb-templates pull request #6
Opened 2020-11-13 15:31 UTC by andresavs

# Principais Alterações no template

- Na pasta research:
    - Foi incluído um arquivo de README com instruções genéricas de como preparar o setup, como usar um notebook e como adicionar um nova biblioteca no arquivo requirements.txt. Além de uma estrutura inicial para adicionar informações e dados do projeto.
    - No arquivo requirements.txt foi adicionadas algumas bibliotecas e algumas tags de exemplo para manter uma estrutura, separando o tipo de biblioteca.

- Na pasta processing (Onde ocorreu a maior parte das mudanças):
    - Temos 4 pastas e cada uma tem um README genérico com algumas informações úteis e itens que devem ser alterados conforme projeto, é mais como um template.
    - Foi disponibilizada uma estrutura inicial de uma API, inclusive um teste.
    - Arquivo requirements.txt possui as bibliotecas necessárias para contruir uma API utilizando FastAPI e Python.

- Na pasta data-science-api:
    - Alteração dos arquivos: env.example e docker-compose.yml.
    - Inclusão dos arquivos: docker-compose-test.yml, Makefile, .gitignore e README.

# Como validar este PR?

1. Crie o arquivo `.env` com as variáveis de ambiente necessárias. Há um template no arquivo .env.example que pode ser usado: `cp .env.example .env`

2. Dê build no projeto 
   ```shell
   docker-compose build  
   ```

3. Suba a aplicação
   ```shell
   docker-compose up  
   ```

4. O container de research precisa subir sem erros e o Jupyter precisa estar funcionando com o Python (a imagem que contempla o R ainda não está disponível). O container de processing também deverá subir sem problemas.

5. Rode os testes do template com `make test` e valide se funcionou. 

6. Dar uma geral nos README e ver se não ficou nada referente aos projetos e clientes DSB, além de avaliar se os textos estão coerentes e  genéricos para um template público.

2020-11-13 16:52 UTC, jonjoncardoso approved these changes

2020-11-16 13:35 UTC, acresende requested changes

2020-11-16 13:35 UTC, acresende commented on data-science-api/processing/api/README.md
> +# TiMiT
Aqui deveria ser genérico como <Nome-do-Projeto>?

2020-11-16 13:52 UTC, andresavs commented on data-science-api/processing/api/README.md
> +# TiMiT
Corrigido!
Deveria estar com uma "variável" como sugestão, <Nome-do-Projeto> - <Nome-da-API>.

2020-11-16 14:00 UTC, acresende approved these changes

2020-11-16 14:01 UTC, merged